name: BLS Monthly Data Pull

on:
  schedule:
    - cron: "55 20 * * *"   # TESTING 
  workflow_dispatch:

jobs:
  data_pull:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Use requirements file

    - name: Run data collection script
      run: |
        python bls_data.py

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add bls_data/*.csv
        git diff --cached --exit-code || git commit -m 'Update BLS data'
        git push
